import {useState} from 'react';
import {ArrowRight,ArrowUpRight,BriefcaseBusiness,Building2,Check,CheckCheck,ChevronDown,Clock3,FileText,Flag,Headphones,Layers3,Mail,MessageSquare,Plus,Search,Send,ShieldCheck,Sparkles,UserRound,Video} from 'lucide-react';
import type {ViewProps} from './model';
import {people} from './model';
import {Avatar,Badge,Button,Field,LinkButton,Note,PageTitle,Panel,Row,SearchField,Stat,Steps} from './ui';
import './AgencyViews.css';

const companies=[
  {name:'Сфера',initial:'С',sector:'B2B · оборудование',signal:'Две вакансии в клиентском отделе',detail:'В открытых вакансиях повторяется задача по обработке входящих обращений. На встрече важно проверить объём заявок и причину потерь.',source:'Вакансии компании · 2 октября',contact:'Ольга · руководитель HR',confidence:'Есть повод для разговора',job:'Менеджер по работе с клиентами'},
  {name:'Атлас',initial:'А',sector:'B2B · логистика',signal:'Открыли новое направление',detail:'Компания объявила о запуске нового направления. Пока неизвестно, планируют ли расширять команду продаж.',source:'Новости компании · 1 октября',contact:'Контакт пока не подтверждён',confidence:'Нужно проверить потребность',job:'Потребность не определена'},
  {name:'Линия',initial:'Л',sector:'B2B · сервисы',signal:'Вакансия опубликована повторно',detail:'Позиция появилась повторно. Это может быть расширение или сложность с наймом. Причину нужно выяснить в разговоре.',source:'Вакансии компании · 30 сентября',contact:'Ирина · HR',confidence:'Нужен разговор с HR',job:'Аккаунт-менеджер'},
];

export function AgencyViews({view,state,update,go,notify}:ViewProps){
  const [query,setQuery]=useState('');
  const [companyIndex,setCompanyIndex]=useState(0);
  const [confirmedCompanies,setConfirmedCompanies]=useState<string[]>([]);
  const [connection,setConnection]=useState<'bitrix'|'outreach'|null>(null);
  const [callNote,setCallNote]=useState('Уточнить, где теряются входящие заявки и какого результата ждут от нового сотрудника.');
  const [tasks,setTasks]=useState<string[]>([]);
  const [candidateQuery,setCandidateQuery]=useState('');
  const [candidateFilter,setCandidateFilter]=useState<'all'|'ready'|'gaps'>('all');
  const [inspected,setInspected]=useState<string|null>(null);
  const [saved,setSaved]=useState<string[]>([]);
  const [interviewer,setInterviewer]=useState('Мария · рекрутер');
  const [evidenceOpen,setEvidenceOpen]=useState(false);
  const [evidenceNote,setEvidenceNote]=useState('Проверить личный вклад в изменение процесса обработки заявок.');
  const [evidenceReviewed,setEvidenceReviewed]=useState(false);
  const [assessmentScore,setAssessmentScore]=useState('4');
  const [followup,setFollowup]=useState('');
  const [followupSent,setFollowupSent]=useState(false);
  const [batchTitle,setBatchTitle]=useState('Первое знакомство · клиентский отдел');
  const [batchNote,setBatchNote]=useState('Анна работала с похожей задачей: сократила время ответа и выстроила распределение входящих заявок. Предлагаем обсудить подход на встрече.');
  const [batchIncluded,setBatchIncluded]=useState(true);
  const [batchSaved,setBatchSaved]=useState(false);
  const [docReference,setDocReference]=useState('Договор с Анной · согласованная версия');
  const [problemOpen,setProblemOpen]=useState(false);
  const [problem,setProblem]=useState('');
  const [problemAction,setProblemAction]=useState<'clarify'|'adapt'|'replace'>('clarify');
  const [problemRecorded,setProblemRecorded]=useState(false);
  const [payment,setPayment]=useState<'pending'|'invoice'|'paid'>('pending');
  const company=companies[companyIndex];
  const signalConfirmed=confirmedCompanies.includes(company.name);
  const toggleTask=(id:string)=>setTasks(old=>old.includes(id)?old.filter(x=>x!==id):[...old,id]);
  const checked=(yes:boolean)=>yes?<Check size={15}/>:<span className="hv-agency-empty-check"/>;
  const anna=people[0];

  if(view==='A01')return <div className="hv-stack">
    <PageTitle eyebrow="Развитие агентства" title="Компании и сигналы" description="Найти реальную потребность, прежде чем предлагать подбор." action={<Button secondary onClick={()=>setConnection(connection==='bitrix'?null:'bitrix')}><Building2 size={16}/> Воронка продаж</Button>}/>
    <div className="hv-grid-3"><Stat label="Компаний на проверке" value="3" note="У каждой свой повод для разговора"/><Stat label="Потребность подтверждена" value={String(confirmedCompanies.length)} note="Сигнал сам по себе не является заказом"/><Stat label="Передано в подбор" value={state.orderCreated?'1':'0'} note="После разговора и согласования задачи"/></div>
    <div className="hv-agency-columns">
      <Panel title="Найти повод для разговора" aside={<Badge>3 компании</Badge>}>
        <SearchField value={query} onChange={setQuery} placeholder="Компания или сигнал"/>
        <div className="hv-agency-company-list">{companies.map((c,i)=>(c.name+' '+c.signal).toLowerCase().includes(query.toLowerCase())&&<button key={c.name} className={`hv-agency-company ${i===companyIndex?'active':''}`} onClick={()=>{setCompanyIndex(i);setConnection(null);}}><span className="hv-agency-company-icon">{c.initial}</span><span><strong>{c.name}</strong><small>{c.sector}</small><span className="hv-agency-signal"><Flag size={13}/>{c.signal}</span></span><ArrowRight size={16}/></button>)}</div>
        {companies.every(c=>!(c.name+' '+c.signal).toLowerCase().includes(query.toLowerCase()))&&<div className="hv-agency-empty"><Search size={24}/><strong>Ничего не нашли</strong><span>Попробуйте название компании или «вакансии».</span><LinkButton onClick={()=>setQuery('')}>Сбросить поиск</LinkButton></div>}
      </Panel>
      <Panel title={company.name} aside={<Badge tone={signalConfirmed?'green':'amber'}>{signalConfirmed?'Потребность подтверждена':company.confidence}</Badge>}>
        <div className="hv-agency-callout"><Flag size={20}/><div><strong>{company.signal}</strong><p>{company.detail}</p><small>{company.source}</small></div></div>
        <div className="hv-agency-facts"><div><span>Контакт</span><strong>{company.contact}</strong></div><div><span>Роль</span><strong>{company.job}</strong></div></div>
        <Field label="Что выяснить в разговоре" value={callNote} onChange={setCallNote} multiline/>
        <div className="hv-actions"><Button secondary onClick={()=>{setConnection('outreach');notify('Открыт план первого обращения');}}><Mail size={16}/> Подготовить обращение</Button><Button secondary onClick={()=>{setConfirmedCompanies(current=>current.includes(company.name)?current:[...current,company.name]);notify('Результат разговора с компанией «'+company.name+'» сохранён');}}>Зафиксировать разговор</Button></div>
        {companyIndex===0&&<div className="hv-agency-next"><div><strong>{state.orderCreated?'Запрос уже передан в работу':'Следующий шаг: запрос на подбор'}</strong><p>Согласовать задачу, условия и ответственного.</p></div><Button onClick={()=>{update({orderCreated:true});go('A02');}}>{state.orderCreated?'Открыть заказ':'Создать запрос'}<ArrowRight size={16}/></Button></div>}
      </Panel>
    </div>
    {connection&&<Panel title={connection==='bitrix'?'Передача в Bitrix':'Первое обращение'} aside={<LinkButton onClick={()=>setConnection(null)}>Закрыть</LinkButton>}><div className="hv-grid-2"><div><Badge tone="purple">Внешний инструмент</Badge><h3>{connection==='bitrix'?'Проверка → разговор → запрос на подбор':'Сообщение под конкретную потребность'}</h3><p className="hv-agency-muted">{connection==='bitrix'?'В Bitrix живут контакты, ответственный за продажи и следующий контакт. Сюда возвращается подтверждённый запрос.':'Повод: '+company.signal.toLowerCase()+'. Цель первого сообщения: выяснить потребность и договориться о коротком разговоре.'}</p></div><div className="hv-agency-callout"><FileText size={21}/><div><strong>{company.name} · карточка для передачи</strong><p>{callNote}</p><Button secondary onClick={()=>notify(connection==='bitrix'?'Карточка подготовлена к передаче в Bitrix':'Черновик обращения сохранён. Отправка не выполнялась')}>{connection==='bitrix'?'Подготовить карточку':'Сохранить черновик'}</Button></div></div></div></Panel>}
  </div>;

  if(view==='A02')return <div className="hv-stack">
    <PageTitle eyebrow="Клиентский заказ · Сфера" title="Заказы и команда" description="Один запрос, понятный результат и ответственный за каждый шаг." action={<Button onClick={()=>go('A03')}>Перейти к кандидатам<ArrowRight size={16}/></Button>}/>
    {!state.orderCreated&&<Note>Запрос ещё не принят в работу. <LinkButton onClick={()=>{update({orderCreated:true});notify('Заказ «Сферы» создан');}}>Создать заказ по этому брифу</LinkButton></Note>}
    <Panel className="hv-agency-order-hero"><div className="hv-agency-order-header"><div className="hv-agency-company-icon large">С</div><div><div className="hv-eyebrow">Сфера · B2B-оборудование</div><h2>Менеджер по работе с клиентами</h2><p>{state.businessResult}</p></div><Badge tone={state.briefApproved?'green':'amber'}>{state.briefApproved?'Бриф согласован':'Ждём согласования брифа'}</Badge></div><div className="hv-agency-order-meta"><div><span>Формат услуги</span><strong>Подбор с сопровождением</strong></div><div><span>Бюджет роли</span><strong>{state.salary}</strong></div><div><span>Целевой выход</span><strong>{state.startDate}</strong></div></div></Panel>
    <div className="hv-grid-2">
      <Panel title="Что должно получиться" aside={<LinkButton onClick={()=>go('E02')}>Открыть согласование</LinkButton>}><div className="hv-agency-brief-block"><span>Задача бизнеса</span><p>{state.businessProblem}</p></div><div className="hv-agency-brief-block"><span>Что проверяем у кандидата</span><p>{state.roleRequirements}</p></div><div className="hv-agency-brief-block"><span>Ожидаемый результат для бизнеса</span><p>{state.businessResult}</p><span>Ориентир первого месяца</span><p>{state.kpi}</p></div><Note>Первую подборку показываем по мере готовности людей. Полную базу собирать для этого не нужно.</Note></Panel>
      <Panel title="Команда и задачи" aside={<Badge>{tasks.length} / 4 выполнено</Badge>}><label className="hv-field"><span>Ответственный за заказ</span><select value={state.owner} onChange={e=>{update({owner:e.target.value});notify('Ответственный обновлён');}}><option>Мария · рекрутер</option><option>Алексей · координатор</option><option>Дарья · интервьюер</option></select></label><div className="hv-agency-task-list">{[{id:'brief',title:'Уточнить критерии и условия',who:'Алексей · с клиентом'},{id:'source',title:'Отобрать кандидатов из базы',who:'Мария · подбор'},{id:'interview',title:'Закрыть пробелы в интервью',who:'Дарья · оценка'},{id:'batch',title:'Подготовить первую подборку',who:state.owner}].map(t=><button key={t.id} className={`hv-agency-task ${tasks.includes(t.id)?'done':''}`} onClick={()=>toggleTask(t.id)}><span className="hv-agency-check">{checked(tasks.includes(t.id))}</span><span><strong>{t.title}</strong><small>{t.who}</small></span></button>)}</div><div className="hv-actions"><Button secondary onClick={()=>go('A04')}>Работа с интервью</Button><Button secondary onClick={()=>go('A05')}>Подборка клиенту</Button></div></Panel>
    </div>
    <Panel title="Где мы сейчас"><Steps items={['Запрос','Бриф','Оценка','Подборка','Выбор','Выход']} current={state.started?5:state.offerSent?4:state.batchSent?3:state.assessmentReady?2:state.briefApproved?1:0}/><p className="hv-agency-muted">Следующий результат: {state.batchSent?'получить решение клиента и назначить встречу.':state.assessmentReady?'проверить согласие кандидата и передать подборку.':'подготовить Анну к первому показу клиенту.'}</p></Panel>
  </div>;

  if(view==='A03'){
    const filtered=people.filter(p=>(p.name+' '+p.experience+' '+p.city).toLowerCase().includes(candidateQuery.toLowerCase())&&(candidateFilter==='all'||candidateFilter==='ready'&&p.ready||candidateFilter==='gaps'&&!p.ready));
    const inspectedPerson=people.find(p=>p.id===inspected);
    return <div className="hv-stack"><PageTitle eyebrow="Единая база" title="Кандидаты" description="Один профиль сохраняет опыт и интервью для разных запросов." action={<Button secondary onClick={()=>{go('C01');}}>Пригласить кандидата<Plus size={16}/></Button>}/>
      <div className="hv-agency-context"><BriefcaseBusiness size={18}/><span>Подбираем для <strong>Сферы</strong></span><span className="hv-agency-separator"/><strong>Менеджер по работе с клиентами</strong><LinkButton onClick={()=>go('A02')}>Бриф</LinkButton></div>
      <Panel><div className="hv-agency-toolbar"><SearchField value={candidateQuery} onChange={setCandidateQuery} placeholder="Имя, опыт или город"/><div className="hv-agency-tabs">{(['all','ready','gaps'] as const).map((f,i)=><button key={f} className={candidateFilter===f?'active':''} onClick={()=>setCandidateFilter(f)}>{['Все кандидаты','Есть интервью','Нужны уточнения'][i]}</button>)}</div></div>
      <div className="hv-agency-candidates">{filtered.map(p=><article className="hv-agency-person" key={p.id}><div className="hv-agency-person-head"><Avatar initials={p.initials}/><div><button className="hv-agency-person-name" onClick={()=>setInspected(inspected===p.id?null:p.id)}>{p.name}</button><p>{p.experience} · {p.city}</p></div><Badge tone={p.id==='max'||p.id==='anna'&&state.assessmentReady?'green':p.ready?'purple':'amber'}>{p.id==='max'||p.id==='anna'&&state.assessmentReady?'Оценка готова':p.ready?'Есть материалы':'Нужна проверка'}</Badge></div><p className="hv-agency-person-summary">{p.id==='anna'?state.candidateExperience:p.summary}</p><div className="hv-agency-person-meta"><span>{p.salary}</span><span><Clock3 size={14}/>{p.id==='anna'?'Ответ до 9 октября':p.id==='max'?'Готов обсудить условия':'Доступность уточняется'}</span><span><ShieldCheck size={14}/>{p.id==='max'||p.id==='anna'&&state.consent?'Показ «Сфере» разрешён':'Разрешение на показ уточняется'}</span></div><div className="hv-agency-person-bottom"><small>{p.id==='anna'&&state.assessmentReady?'Проверенные материалы можно использовать для подбора.':p.gap}</small><div className="hv-actions"><Button secondary onClick={()=>{setSaved(s=>s.includes(p.id)?s.filter(x=>x!==p.id):[...s,p.id]);notify(saved.includes(p.id)?'Кандидат убран из списка интереса':'Кандидат сохранён для этого запроса');}}>{saved.includes(p.id)?<Check size={15}/>:<Plus size={15}/>} {saved.includes(p.id)?'Сохранён':'В список'}</Button><Button onClick={()=>{if(p.id==='anna'){update({selected:'anna'});go('A04');}else setInspected(p.id);}}>{p.id==='anna'?'Подготовить к показу':'Посмотреть профиль'}<ArrowRight size={15}/></Button></div></div></article>)}</div>
      {!filtered.length&&<div className="hv-agency-empty"><Search size={27}/><strong>По этим условиям нет кандидатов</strong><span>Уберите фильтр или измените поисковый запрос.</span><Button secondary onClick={()=>{setCandidateQuery('');setCandidateFilter('all');}}>Сбросить фильтры</Button></div>}</Panel>
      {inspectedPerson&&<Panel title={inspectedPerson.name} aside={<LinkButton onClick={()=>setInspected(null)}>Закрыть профиль</LinkButton>}><div className="hv-grid-2"><div><h3>Что уже известно</h3><p>{inspectedPerson.summary}</p><p className="hv-agency-muted">{inspectedPerson.experience}. Ожидания: {inspectedPerson.salary}.</p></div><div className="hv-agency-callout"><MessageSquare size={20}/><div><strong>Следующее уточнение</strong><p>{inspectedPerson.gap}. {inspectedPerson.id==='max'?'Согласие на показ «Сфере» и интерес подтверждены. Уточняем гибкость по оплате.':'Перед показом компании отдельно подтвердить интерес и согласие.'}</p><Button secondary onClick={()=>notify('Задача на уточнение профиля добавлена в локальную очередь')}>Добавить задачу на уточнение</Button></div></div></div></Panel>}
      <Note>Профиль общий для разных вакансий. Согласие на показ, интерес и решение клиента фиксируются для каждого подбора отдельно.</Note>
    </div>;
  }

  if(view==='A04')return <div className="hv-stack">
    <PageTitle eyebrow="Оценка кандидата · Сфера" title="Интервью и оценка" description="Сначала материал и доказательства, затем вывод о соответствии роли." action={<Button secondary onClick={()=>go('A03')}>К базе кандидатов</Button>}/>
    <div className="hv-agency-candidate-strip"><Avatar initials="АМ" large/><div><h2>Анна Миронова</h2><p>Профиль для вакансии «Менеджер по работе с клиентами»</p></div><div className="hv-agency-strip-badges"><Badge tone={state.assessmentReady?'green':'amber'}>{state.assessmentReady?'Оценка проверена':'Профиль в работе'}</Badge><Badge tone={state.consent?'green':'neutral'}>{state.consent?'Согласие получено':'Согласие отдельно'}</Badge></div></div>
    <Panel title="Что кандидат рассказал о себе"><Row title="Опыт" detail={state.candidateExperience}/><Row title="Ожидания" detail={state.candidateExpectations}/></Panel>{state.clarifications.anna&&<Note><strong>Запрос работодателя на уточнение:</strong> {state.clarifications.anna}</Note>}<Steps items={['Маршрут интервью','Материалы','Проверка оценки','Готов к показу']} current={state.assessmentReady?3:state.interviewDone?2:state.interviewRoute?1:0}/>
    <div className="hv-agency-columns">
      <div className="hv-stack"><Panel title="Как соберём материал"><div className="hv-agency-route-choice"><button className={state.interviewRoute==='hr'?'active':''} onClick={()=>{update({interviewRoute:'hr'});notify('Выбрано интервью с рекрутером');}}><Headphones size={22}/><strong>С рекрутером</strong><span>Живой разговор и уточнения</span>{state.interviewRoute==='hr'&&<Check size={16}/>}</button><button className={state.interviewRoute==='ai'?'active':''} onClick={()=>{update({interviewRoute:'ai'});notify('Выбран внешний AI-сервис');}}><Sparkles size={22}/><strong>AI-интервью</strong><span>Внешний сервис, проверяем результат</span>{state.interviewRoute==='ai'&&<Check size={16}/>}</button></div><label className="hv-field"><span>Кто проверит результат</span><select value={interviewer} onChange={e=>setInterviewer(e.target.value)}><option>Мария · рекрутер</option><option>Дарья · интервьюер</option><option>Алексей · координатор</option></select></label><div className="hv-actions"><Button secondary onClick={()=>go('C02')}>Открыть задание кандидата<ArrowUpRight size={16}/></Button></div></Panel>
      <Panel title="Материалы интервью" aside={<Badge tone={state.interviewDone?'green':'neutral'}>{state.interviewDone?'Материал получен':'Ожидаем'}</Badge>}>{state.interviewDone?<><div className="hv-agency-material"><div className="hv-agency-material-icon"><Video size={25}/></div><div><strong>Опыт работы с входящими обращениями</strong><small>Интервью · 24 минуты · расшифровка</small></div><Badge>Готово</Badge></div><button className="hv-agency-evidence-toggle" onClick={()=>setEvidenceOpen(!evidenceOpen)}><span><Badge tone="purple">06:42</Badge>Как изменила обработку заявок</span><ChevronDown size={17}/></button>{evidenceOpen&&<blockquote className="hv-agency-quote">{state.interviewAnswer||'«Мы распределили обращения по ответственным и ввели правило первого ответа. Я каждое утро проверяла зависшие заявки и причины задержек».'}<small>Фрагмент ответа Анны · материал для проверки оценки</small></blockquote>}<Field label="Заметка проверяющего" value={evidenceNote} onChange={setEvidenceNote} multiline/><button className={`hv-agency-task ${evidenceReviewed?'done':''}`} onClick={()=>setEvidenceReviewed(!evidenceReviewed)}><span className="hv-agency-check">{checked(evidenceReviewed)}</span><span><strong>Проверила вывод по первичному материалу</strong><small>Ответ действительно подтверждает оценку</small></span></button></>:<div className="hv-agency-empty"><Video size={28}/><strong>Интервью ещё не завершено</strong><span>Выберите маршрут и передайте задание кандидату. Если разговор уже прошёл, добавьте его результат.</span><Button disabled={!state.interviewRoute} onClick={()=>{update({interviewDone:true});setEvidenceOpen(true);notify('Пример результата интервью добавлен для разбора');}}>Добавить результат интервью</Button>{!state.interviewRoute&&<small>Сначала выберите рекрутера или AI-интервью выше.</small>}</div>}</Panel></div>
      <div className="hv-stack"><Panel title="Оценка по требованиям роли" aside={<Badge>3 критерия</Badge>}><div className="hv-agency-criterion"><div><strong>Работа с входящими заявками</strong><p>Есть пример изменения процесса и личного участия.</p></div><label className="hv-agency-score"><select aria-label="Оценка работы с входящими заявками" value={assessmentScore} onChange={e=>setAssessmentScore(e.target.value)} disabled={!state.interviewDone}><option value="0">?</option><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option><option value="5">5</option></select><small>/ 5</small></label></div><Row title="Диалог с B2B-клиентом" detail={state.interviewDone?'Привела пример сложного разговора с заказчиком':'Ждём материал интервью'} aside={<Badge tone={state.interviewDone?'purple':'neutral'}>{state.interviewDone?'4 / 5':'Нет данных'}</Badge>}/><Row title="Системность" detail={state.interviewDone?'Описала контроль сроков и разбор задержек':'Ждём материал интервью'} aside={<Badge tone={state.interviewDone?'purple':'neutral'}>{state.interviewDone?'4 / 5':'Нет данных'}</Badge>}/><div className="hv-agency-assessment-footer"><strong>Пробел ≠ низкая оценка</strong><p>Если данных не хватает, задаём уточнение. Не подменяем отсутствие ответа нулём.</p></div></Panel>
      <Panel title="Что ещё уточнить"><Field label="Вопрос кандидату" value={followup} onChange={v=>{setFollowup(v);setFollowupSent(false);}} multiline/><div className="hv-actions"><Button secondary disabled={!followup.trim()} onClick={()=>{setFollowupSent(true);notify('Уточнение добавлено к следующему контакту');}}>{followupSent?<Check size={16}/>:<Plus size={16}/>} {followupSent?'Уточнение добавлено':'Добавить уточнение'}</Button></div><p className="hv-agency-muted">Обязательный пробел можно закрыть коротким вопросом или кейсом, без повторения всего интервью.</p></Panel>
      <Panel className="hv-agency-finish"><ShieldCheck size={25}/><h3>{state.assessmentReady?'Анна готова к подборке':'Проверить и завершить оценку'}</h3><p>{state.assessmentReady?'Осталось проверить разрешение на показ клиенту и подготовить пояснение.':'Материалы и выводы проверяет человек. Согласие на показ сохраняется отдельным условием.'}</p><Button disabled={!state.interviewDone} onClick={()=>{update({assessmentReady:true});notify('Оценка проверена и готова к использованию');go('A05');}}>{state.assessmentReady?'Перейти к подборке':'Подтвердить оценку'}<ArrowRight size={16}/></Button>{!state.interviewDone&&<small>Сначала нужен завершённый материал интервью.</small>}</Panel></div>
    </div>
  </div>;

  if(view==='A05'){
    const ready=state.consent&&state.assessmentReady&&batchIncluded&&state.candidateInterest;
    return <div className="hv-stack"><PageTitle eyebrow="Сфера · менеджер по работе с клиентами" title="Подборка для клиента" description="Показываем готовых людей небольшими порциями и уточняем подбор по обратной связи." action={state.batchSent?<Button onClick={()=>go('E03')}>Посмотреть глазами клиента<ArrowUpRight size={16}/></Button>:<Button disabled={!ready} onClick={()=>{update({batchSent:true});notify('Подборка опубликована в кабинете клиента');}}><Send size={16}/> Опубликовать подборку</Button>}/>
      {state.batchSent&&<div className="hv-agency-success"><span><CheckCheck size={24}/></span><div><strong>{state.candidateInterest?'Подборка доступна клиенту':'Подборка передана · интерес Анны изменился'}</strong><p>{state.candidateInterest?'Анна и Максим переданы на рассмотрение. Следующий шаг: получить решение и предложить встречу.':'Анна больше не рассматривает вакансию. Нужно уточнить причину и предупредить клиента; по Максиму работа продолжается.'}</p></div><Badge tone="green">Передано</Badge></div>}
      {!state.candidateInterest&&<Note><strong>Показ Анны приостановлен.</strong> Кандидат больше не рассматривает эту вакансию. Уточните причину и подтвердите актуальный интерес перед новой публикацией. <LinkButton onClick={()=>go('C03')}>Открыть ответ кандидата</LinkButton></Note>}<div className="hv-agency-columns"><div className="hv-stack"><Panel title="Состав подборки" aside={<Badge>{batchIncluded?'2 кандидата':'1 кандидат · черновик'}</Badge>}><article className="hv-agency-person compact"><div className="hv-agency-person-head"><Avatar initials={anna.initials}/><div><strong>{anna.name}</strong><p>{anna.experience}</p></div><button className={`hv-agency-check-toggle ${batchIncluded?'active':''}`} aria-label={batchIncluded?'Убрать Анну из подборки':'Добавить Анну в подборку'} onClick={()=>{if(state.batchSent){notify('Опубликованная подборка сохранена; изменения войдут в следующую версию');return;}setBatchIncluded(!batchIncluded);}}>{batchIncluded?<Check size={16}/>:<Plus size={16}/>}</button></div><p>{state.candidateExperience}</p><div className="hv-agency-tags"><Badge tone={state.assessmentReady?'green':'amber'}>{state.assessmentReady?'Оценка готова':'Оценка не завершена'}</Badge><Badge tone={state.consent?'green':'amber'}>{state.consent?'Показ разрешён':'Нет согласия на показ'}</Badge><Badge>{state.salary}</Badge></div><LinkButton onClick={()=>go('A04')}>Открыть оценку</LinkButton></article><article className="hv-agency-person compact hv-agency-published-profile"><div className="hv-agency-person-head"><Avatar initials="МЛ"/><div><strong>Максим Лебедев</strong><p>7 лет в B2B-продажах</p></div><Badge tone="green">Уже подготовлен</Badge></div><p>Опыт длинных B2B-сделок и переговоров с производственными компаниями. Условия оплаты нужно обсудить: ожидания от 180 000 ₽.</p><div className="hv-agency-tags"><Badge tone="green">Оценка проверена</Badge><Badge tone="green">Показ «Сфере» разрешён</Badge></div><small className="hv-agency-muted">Отдельное согласие и проверка сохранены в существующем профиле. Изменения интервью Анны на этот профиль не влияют.</small></article><div className="hv-agency-quiet-row"><Layers3 size={18}/><div><strong>Елену добавим после уточнений</strong><p>Нужен пример работы с новым клиентом. Не задерживаем готовую подборку.</p></div><LinkButton onClick={()=>go('A03')}>База</LinkButton></div></Panel><Panel title="Как объясним выбор"><Field label="Название подборки" value={batchTitle} onChange={setBatchTitle}/><Field label="Сопроводительная заметка клиенту" value={batchNote} onChange={setBatchNote} multiline/><Button secondary onClick={()=>{setBatchSaved(true);notify('Заметка и название подборки сохранены');}}>{batchSaved?<Check size={16}/>:<FileText size={16}/>} {batchSaved?'Черновик сохранён':'Сохранить черновик'}</Button></Panel></div>
      <div className="hv-stack"><Panel title="Перед публикацией"><div className="hv-agency-readiness-row"><span className={state.assessmentReady?'complete':''}>{checked(state.assessmentReady)}</span><div><strong>Оценка подтверждена</strong><p>Есть материалы и проверенные выводы.</p>{!state.assessmentReady&&<LinkButton onClick={()=>go('A04')}>Завершить оценку</LinkButton>}</div></div><div className="hv-agency-readiness-row"><span className={state.consent?'complete':''}>{checked(state.consent)}</span><div><strong>Анна разрешила показ «Сфере»</strong><p>Согласие привязано к этому работодателю. Разрешение Максима уже сохранено отдельно.</p>{!state.consent&&<LinkButton onClick={()=>go('C01')}>Открыть приглашение кандидата</LinkButton>}</div></div><div className="hv-agency-readiness-row"><span className={state.candidateInterest?'complete':''}>{checked(state.candidateInterest)}</span><div><strong>Интерес кандидата актуален</strong><p>{state.candidateInterest?'Анна продолжает рассматривать эту вакансию.':'Показ приостановлен: нужно уточнить изменившиеся ожидания.'}</p>{!state.candidateInterest&&<LinkButton onClick={()=>go('C03')}>Открыть ответ кандидата</LinkButton>}</div></div><div className="hv-agency-readiness-row"><span className={batchIncluded?'complete':''}>{checked(batchIncluded)}</span><div><strong>Состав подборки подтверждён</strong><p>Анна и Максим, у каждого свой профиль и основания оценки.</p></div></div><div className="hv-agency-deadline"><Clock3 size={19}/><div><strong>{state.candidateDeadline}</strong><p>У Анны параллельно идут другие процессы. Уточним срок решения у клиента.</p></div></div></Panel><Panel title="Что увидит клиент"><div className="hv-agency-preview"><div className="hv-eyebrow">{batchTitle}</div><h3>Анна Миронова</h3><p>{batchNote}</p><div className="hv-agency-tags"><Badge>Опыт</Badge><Badge>Доказательства</Badge><Badge>Оценка по роли</Badge></div></div><p className="hv-agency-muted">Внутренние рабочие заметки остаются у команды.</p></Panel></div></div>
      {state.batchSent&&<Panel title="Обратная связь по подборке"><Row title="Анна Миронова" detail={state.decisions.anna?`Решение зафиксировано: ${{invite:'пригласить на встречу',rejected:'отказ',clarify:'уточнить опыт'}[state.decisions.anna]||'получен ответ клиента'}`:'Ожидаем первое решение клиента'} aside={<Badge tone={state.decisions.anna?'green':'amber'}>{state.decisions.anna?'Есть ответ':'На рассмотрении'}</Badge>}/>{state.reasons.anna&&<Note>{state.reasons.anna}</Note>}<Row title="Максим Лебедев" detail={state.decisions.max?`Решение зафиксировано: ${{invite:'пригласить на встречу',rejected:'отказ',clarify:'уточнить опыт'}[state.decisions.max]||'получен ответ клиента'}`:'Ожидаем первое решение клиента'} aside={<Badge tone={state.decisions.max?'green':'amber'}>{state.decisions.max?'Есть ответ':'На рассмотрении'}</Badge>}/>{state.reasons.max&&<Note>{state.reasons.max}</Note>}<div className="hv-actions"><Button secondary onClick={()=>go('A06')}>Сопровождать следующий шаг</Button><Button secondary onClick={()=>go('E03')}>Открыть клиентскую подборку</Button></div></Panel>}
    </div>;
  }

  if(view==='A06'){
    const employerRejected=state.decisions.anna==='rejected';
    const processPaused=!state.candidateInterest||employerRejected||state.offerResponse==='declined';
    const pauseReason=employerRejected?'Работодатель отказал кандидату':state.offerResponse==='declined'?'Анна отказалась от оффера':'Анна больше не рассматривает вакансию';
    const canStart=state.offerResponse==='accepted'&&state.documentsReady&&state.candidateInterest&&!employerRejected;
    const stage=state.started?4:state.offerResponse==='accepted'?3:state.offerSent?2:(state.meetings.anna||state.meeting)?1:0;
    return <div className="hv-stack"><PageTitle eyebrow="Сфера · Анна Миронова" title="Сопровождение до результата" description="Согласованный оффер, готовность сторон и фактический выход фиксируются отдельно." action={<Button secondary onClick={()=>go('H04')}>Встречи и контакты<ArrowRight size={16}/></Button>}/>
      <div className="hv-agency-candidate-strip"><Avatar initials="АМ" large/><div><h2>Анна Миронова → Сфера</h2><p>Менеджер по работе с клиентами · ответственный: {state.owner}</p></div><Badge tone={processPaused?'amber':state.started?'green':'purple'}>{processPaused?'Процесс приостановлен':state.started?'Вышла на работу':'Сопровождаем процесс'}</Badge></div>
      {processPaused&&<Note><strong>{pauseReason}.</strong> {employerRejected?(state.reasons.anna||'Нужно запросить причину и уточнить следующий подбор.'):(state.declineReason||'Уточнить причину и дальнейшие ожидания кандидата.')} <LinkButton onClick={()=>{setProblemOpen(true);setProblem(employerRejected?(state.reasons.anna||pauseReason):(state.declineReason||pauseReason));}}>Разобрать причину</LinkButton></Note>}{state.offerResponse==='counter'&&<Note><strong>Встречные условия Анны:</strong> {state.counterProposal||'Нужно уточнить пожелания кандидата.'} <LinkButton onClick={()=>go('E05')}>Обсудить с работодателем</LinkButton></Note>}<Panel><Steps items={['Рассмотрение','Встреча','Оффер','Подготовка','Выход']} current={stage}/></Panel>
      <div className="hv-grid-3"><Stat label="Условия" value={state.salary} note={state.offerApproved?'Согласованы работодателем':'Ожидают согласования'}/><Stat label="Плановый выход" value={state.startDate} note={state.started?'Фактический выход подтверждён':'Уточняем готовность обеих сторон'}/><Stat label="Интерес кандидата" value={!state.candidateInterest?'Не рассматривает':employerRejected?'Отказ работодателя':state.offerResponse==='accepted'?'Оффер принят':state.offerResponse==='counter'?'Обсуждает условия':state.offerResponse==='declined'?'Отказалась':'В процессе'} note={state.candidateDeadline}/></div>
      <div className="hv-agency-columns"><div className="hv-stack"><Panel title="Договорённости и готовность"><Row title="Условия согласованы работодателем" detail={state.offerApproved?'Есть утверждённая версия предложения':'Работодатель утверждает зарплату, задачи и условия'} aside={<Badge tone={state.offerApproved?'green':'amber'}>{state.offerApproved?'Готово':'Нужно решение'}</Badge>}/><Row title="Предложение передано кандидату" detail={state.offerSent?'Кандидат может изучить условия и ответить':'После согласования условий'} aside={<Badge tone={state.offerSent?'green':'neutral'}>{state.offerSent?'Передано':'Ожидаем'}</Badge>}/><Row title="Ответ кандидата" detail={!state.candidateInterest?'Анна больше не рассматривает эту вакансию':state.offerResponse==='accepted'?'Анна приняла предложение':state.offerResponse==='counter'?(state.counterProposal||'Нужно обсудить встречные условия'):state.offerResponse==='declined'?(state.declineReason||'Нужно разобраться в причине отказа'):'Ответ пока не получен'} aside={<Badge tone={state.candidateInterest&&state.offerResponse==='accepted'?'green':'amber'}>{!state.candidateInterest?'Не рассматривает':state.offerResponse==='accepted'?'Принято':state.offerResponse==='declined'?'Отказ':'В работе'}</Badge>}/><div className="hv-actions"><Button secondary onClick={()=>go('E05')}>Открыть условия работодателя</Button><Button secondary onClick={()=>go('C03')}>Страница кандидата</Button></div></Panel>
      <Panel title="Подготовка документов" aside={<Badge tone={state.documentsReady?'green':'neutral'}>{state.documentsReady?'Готовы':'В работе'}</Badge>}><p className="hv-agency-muted">Документы готовит и подписывает работодатель. Здесь храним название согласованной версии и состояние оформления.</p><Field label="Документ или ссылка на согласованную версию" value={docReference} onChange={setDocReference}/><Button secondary disabled={!docReference.trim()} onClick={()=>{update({documentsReady:!state.documentsReady});notify(state.documentsReady?'Документы возвращены на проверку':'Готовность документов отмечена');}}>{state.documentsReady?'Вернуть на проверку':'Отметить готовность документов'}</Button></Panel>
      <Panel title="Фактический выход"><div className="hv-agency-start"><div className={`hv-agency-start-icon ${state.started?'complete':''}`}>{state.started?<CheckCheck size={27}/>:<UserRound size={27}/>}</div><div><h3>{state.started?'Анна приступила к работе':processPaused?'Выход приостановлен':'Проверить, что человек действительно вышел'}</h3><p>{state.started?'Теперь собираем обратную связь и проверяем, совпали ли ожидания сторон.':processPaused?'Сначала нужно разрешить причину остановки процесса. Готовность документов сама по себе не означает готовность к выходу.':'Подтверждаем с кандидатом и работодателем. Принятого оффера для этого недостаточно.'}</p></div></div><div className="hv-actions"><Button disabled={!canStart||state.started} onClick={()=>{update({started:true});notify('Фактический выход Анны подтверждён');}}>{state.started?'Выход подтверждён':'Подтвердить фактический выход'}</Button></div>{!canStart&&<div className="hv-agency-prerequisites">{!state.candidateInterest&&<span>• Кандидат больше не рассматривает вакансию</span>}{employerRejected&&<span>• Работодатель отказал кандидату</span>}{state.offerResponse!=='accepted'&&<span>• Нужен принятый кандидатом оффер</span>}{!state.documentsReady&&<span>• Нужно завершить подготовку документов</span>}</div>}</Panel></div>
      <div className="hv-stack"><Panel title="Не потерять взаимный интерес"><div className="hv-agency-deadline"><Clock3 size={20}/><div><strong>{state.candidateDeadline}</strong><p>{processPaused?'Уточнить причину остановки процесса и согласовать дальнейшие действия.':'Уточнить решение клиента до следующего контакта с Анной.'}</p></div></div><Row title="Следующий контакт" detail={processPaused?'Разобрать причину и согласовать дальнейшие действия':state.meetings.anna||state.meeting||'Согласовать короткую встречу с руководителем'} aside={<Badge>Координатор</Badge>}/><Button secondary onClick={()=>go('H04')}>Назначить следующий шаг</Button></Panel><Panel title="Результат услуги и расчёты"><div className="hv-agency-facts"><div><span>Услуга</span><strong>Подбор с сопровождением</strong></div><div><span>Состояние расчёта</span><Badge tone={payment==='paid'?'green':payment==='invoice'?'purple':'neutral'}>{payment==='paid'?'Оплата отмечена':payment==='invoice'?'Счёт подготовлен':'Условия требуют проверки'}</Badge></div></div><p className="hv-agency-muted">Основание и срок оплаты проверяем по договорённости с клиентом. Счёт и платёж оформляются во внешней системе.</p><Button secondary onClick={()=>{setPayment(payment==='pending'?'invoice':payment==='invoice'?'paid':'pending');notify(payment==='pending'?'Подготовка счёта отмечена':payment==='invoice'?'Поступление оплаты отмечено':'Статус расчёта сброшен');}}>{payment==='pending'?'Отметить подготовку счёта':payment==='invoice'?'Отметить поступление оплаты':'Вернуть статус на проверку'}</Button></Panel><Panel title="Если ожидания не совпали"><p className="hv-agency-muted">Сначала выясняем причину и возможность исправить ситуацию. Замена является отдельным решением по условиям услуги.</p><Button secondary onClick={()=>setProblemOpen(!problemOpen)}>{problemOpen?'Закрыть разбор':'Разобрать проблему'}</Button>{problemOpen&&<div className="hv-agency-problem"><Field label="Что произошло" value={problem} onChange={v=>{setProblem(v);setProblemRecorded(false);}} multiline/><label className="hv-field"><span>Следующий шаг</span><select value={problemAction} onChange={e=>setProblemAction(e.target.value as 'clarify'|'adapt'|'replace')}><option value="clarify">Собрать обратную связь сторон</option><option value="adapt">Уточнить задачи и план адаптации</option><option value="replace">Проверить условия замены</option></select></label><Button disabled={!problem.trim()} onClick={()=>{setProblemRecorded(true);if(problemAction==='replace')update({replacement:true});notify(problemAction==='replace'?'Запрос на проверку условий замены зарегистрирован':'Следующий шаг по проблеме сохранён');}}>{problemRecorded?'Шаг сохранён':'Зафиксировать следующий шаг'}</Button>{(state.replacement||problemRecorded)&&<Note>{state.replacement?'Запрос на замену требует проверки условий услуги. Новая подборка ещё не запущена.':'Причина и следующий шаг сохранены. Координатор вернётся с результатом.'}</Note>}</div>}</Panel></div></div>
    </div>;
  }
  return null;
}
