import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,BriefcaseBusiness,Check,ChevronRight,Compass,LayoutGrid,RotateCcw,Sparkles} from 'lucide-react';
import {MotionConfig,motion} from 'motion/react';
import {ManagerViews} from './ManagerViews';
import {AgencyViews} from './AgencyViews';
import {CandidateViews,HRViews} from './PeopleViews';
import {initialState,roles,views,type DemoState,type Role,type ViewId} from './model';
import './hr-vision.css';
const journey:ViewId[]=['A01','A02','E02','A03','C01','C02','A04','A05','E03','E04','H04','E05','C03','A06'];
export function preset(view:ViewId):DemoState{
 const draft={...initialState,decisions:{},reasons:{}};
 if(['A01','A02','E02','C01'].includes(view))return draft;
 const ready={...draft,orderCreated:true,briefApproved:true,consent:true,interviewRoute:'hr' as const,interviewDone:true,assessmentReady:true};
 if(['A03','A04','A05','C02'].includes(view))return {...ready,assessmentReady:view!=='A04',interviewDone:view!=='C02'};
 const published={...ready,batchSent:true};
 if(view==='E05'||view==='H04')return {...published,decisions:{anna:'invite'},meeting:'7 октября · 14:00',meetings:{anna:'7 октября · 14:00'}};
 if(view==='C03'||view==='C04')return {...published,decisions:{anna:'invite'},meeting:'7 октября · 14:00',meetings:{anna:'7 октября · 14:00'},offerApproved:true,offerSent:true};
 if(view==='A06')return {...published,decisions:{anna:'invite'},meeting:'7 октября · 14:00',meetings:{anna:'7 октября · 14:00'},offerApproved:true,offerSent:true,offerResponse:'accepted'};
 return published;
}
export function HRVisionLab({initialView='E04',fresh=false,compact=false,playing=false,runId=0,onManualInteraction}:{initialView?:ViewId;fresh?:boolean;compact?:boolean;playing?:boolean;runId?:number;onManualInteraction?:()=>void}){
 const [view,setView]=useState<ViewId>(initialView);const [state,setState]=useState<DemoState>(()=>fresh?{...initialState}:preset(initialView));
 const [lastViews,setLastViews]=useState<Record<Role,ViewId>>({manager:'E04',hr:'H01',agency:'A01',candidate:'C01'});
 const [toast,setToast]=useState('');const [resetId,setResetId]=useState(0);const [map,setMap]=useState(false);const [help,setHelp]=useState(false);const [trail,setTrail]=useState<ViewId[]>([]);const [walk,setWalk]=useState(false);const [manual,setManual]=useState(false);const contentRef=useRef<HTMLElement>(null);
 const current=views.find(s=>s.id===view)!;const role=current.role;
 useEffect(()=>{setView(initialView);setState(fresh?{...initialState}:preset(initialView));setResetId(n=>n+1);setTrail([]);setToast('');setMap(false);setHelp(false);setWalk(false);setManual(false);setLastViews({manager:'E04',hr:'H01',agency:'A01',candidate:'C01'})},[runId,initialView,fresh]);
 useEffect(()=>{contentRef.current?.scrollTo({top:0});},[view,resetId]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),6500);return()=>clearTimeout(t)},[toast]);
 useEffect(()=>{if(!playing||manual)return;let index=0;const timer=setInterval(()=>{const id=journey[index%journey.length];setView(id);setState(preset(id));index++},3500);return()=>clearInterval(timer)},[playing,manual,runId]);
 const manualAction=()=>{setManual(true);onManualInteraction?.()};
 const go=(id:ViewId)=>{manualAction();setTrail(a=>[...a,view]);setView(id);setLastViews(v=>({...v,[views.find(s=>s.id===id)!.role]:id}));setMap(false);setToast('')};
 const update=(patch:Partial<DemoState>)=>setState(s=>({...s,...patch}));
 const notify=(message:string)=>setToast(message);
 const reset=()=>{manualAction();setState(fresh?{...initialState}:preset(initialView));setView(initialView);setTrail([]);setToast('');setMap(false);setHelp(false);setResetId(n=>n+1);setWalk(false)};
 const begin=()=>{manualAction();setState({...initialState,decisions:{},reasons:{}});setView('A01');setTrail([]);setResetId(n=>n+1);setMap(false);setWalk(true);setToast('Начали с сигнала компании. Действия сохраняются при переключении участников.')};
 const props={view,state,update,go,notify};
 const roleView=(r:Role)=>({...props,view:role===r?view:lastViews[r]});
 const next:Record<Role,{id:ViewId;label:string}>={agency:{id:state.batchSent?'E03':'C01',label:state.batchSent?'Посмотреть глазами клиента':'Посмотреть приглашение кандидата'},manager:{id:state.offerApproved?'H04':'A05',label:state.offerApproved?'Передать следующий шаг HR':'Посмотреть работу агентства'},hr:{id:state.offerSent?'C03':'E04',label:state.offerSent?'Посмотреть предложение кандидату':'Посмотреть глазами руководителя'},candidate:{id:state.offerResponse==='accepted'?'A06':'A04',label:state.offerResponse==='accepted'?'Посмотреть сопровождение выхода':'Посмотреть работу рекрутера'}};
 return <MotionConfig reducedMotion="user"><div className={`hv-lab ${compact?'hv-compact':''}`} onPointerDownCapture={()=>{if(playing)manualAction()}}>
 <div className="hv-lab-bar"><a className="hv-lab-label" href="/?path=/story/hr-vision-agency--overview" target="_top"><LayoutGrid size={14}/>interface lab</a><span className="hv-lab-divider"/><strong>HR Vision / Агентство</strong><span className="hv-lab-disclaimer">Все данные вымышлены · действия симулируются</span><a className="hv-cjm-link" href="/iframe.html?id=hr-vision-cjm--agency&viewMode=story"><Compass size={14}/>CJM</a><a className="hv-cjm-link" href="/iframe.html?id=hr-vision-xpm--overview&viewMode=story">XPM</a><button onClick={()=>setHelp(v=>!v)} className={help?'active':''}>Как смотреть</button><button onClick={()=>setMap(v=>!v)} className={map?'active':''}><Compass size={14}/>Все экраны · 19</button><button onClick={reset} aria-label="Сбросить пример"><RotateCcw size={14}/></button></div>
 <div className="hv-role-strip"><span>Смотреть от лица</span><div role="group" aria-label="Участник процесса">{(Object.keys(roles) as Role[]).map(r=><button key={r} className={role===r?'active':''} onClick={()=>go(views.find(s=>s.role===r)!.id)}>{roles[r]}</button>)}</div><button className="hv-start-walk" onClick={begin}><ArrowRight size={14}/>С начала процесса</button></div>
 {help&&<div className="hv-help"><strong>Один процесс, разные стороны.</strong><p>Слева экраны текущего участника. Сверху можно сменить роль и увидеть результат действия. «С начала процесса» очищает пример и проводит от сигнала компании до выхода человека. «Все экраны» показывает общую структуру. Фиолетовая панель рассмотрения развивает вашу исходную витрину кандидатов.</p><p>Вместо настоящего видео показано содержание фрагмента. Bitrix, AI-интервью, сообщения, оплата и документы здесь представлены локальными примерами. Оффер и кабинет поиска показывают целевое развитие.</p></div>}
 {map&&<main className="hv-map"><div className="hv-map-heading"><span className="hv-eyebrow">СТРУКТУРА / АГЕНТСКИЙ ПОДБОР</span><h1>Одна услуга. Четыре точки зрения.</h1><p>Нажмите на экран, чтобы посмотреть его в контексте текущего процесса.</p></div><div className="hv-map-columns">{(Object.keys(roles) as Role[]).map(r=><section key={r}><h2>{roles[r]}<span>{views.filter(v=>v.role===r).length}</span></h2>{views.filter(v=>v.role===r).map(v=><button key={v.id} onClick={()=>go(v.id)}><span>{v.id}</span><strong>{v.name}</strong><p>{v.job}</p>{v.future&&<small>Развитие продукта</small>}<ChevronRight size={16}/></button>)}</section>)}</div></main>}<div className="hv-product" hidden={map}>
 <header className="hv-product-header"><div className="hv-wordmark"><span><BriefcaseBusiness size={18}/></span>HR Vision</div><div className="hv-workspace-label">{role==='agency'?'Рабочее пространство команды':role==='candidate'?'Ваш следующий шаг':'Сфера / Кабинет компании'}</div><div className="hv-product-user"><span className="hv-user-dot">{role==='candidate'?'АМ':role==='agency'?'МК':'ИП'}</span>{role==='candidate'?'Анна Миронова':role==='agency'?'Мария Ковалева':'Иван Петров'}</div></header>
 <div className={`hv-product-body ${role==='candidate'?'candidate':''}`}><aside className="hv-sidebar"><div className="hv-sidebar-label">{role==='manager'?'Найм в вашей команде':role==='hr'?'Подбор в компании':role==='agency'?'Агентский подбор':'Мои возможности'}</div><nav aria-label="Экраны участника">{views.filter(s=>s.role===role).map(s=><button key={s.id} className={view===s.id?'active':''} onClick={()=>go(s.id)}><span>{s.name}</span>{view===s.id&&<ChevronRight size={14}/>}</button>)}</nav><div className="hv-sidebar-context"><span className="hv-eyebrow">Текущий запрос</span><strong>Менеджер по работе с клиентами</strong><p>Сфера · B2B-продажи</p><span className="hv-sidebar-status"><i/>{state.started?'Человек вышел':state.offerResponse==='accepted'?'Готовимся к выходу':state.offerSent?'Оффер у кандидата':state.batchSent?'Рассмотрение':state.briefApproved?'Готовим подборку':'Уточняем задачу'}</span></div><div className="hv-sidebar-bottom"><ShieldIcon/>Интервью становится основой профиля для подходящих ролей.</div></aside>
 <main className="hv-content" ref={contentRef}><div className="hv-screen-context"><span>{current.id} / {current.job}</span>{current.future&&<span className="hv-target">Целевое развитие</span>}{trail.length>0&&<button onClick={()=>{const prev=trail[trail.length-1];setTrail(t=>t.slice(0,-1));setView(prev);setToast('')}}><ArrowLeft size={13}/>Назад</button>}</div><motion.div key={resetId} initial={{opacity:0,y:5}} animate={{opacity:1,y:0}} transition={{duration:.18}}><div hidden={role!=='agency'}><AgencyViews {...roleView('agency')}/></div><div hidden={role!=='candidate'}><CandidateViews {...roleView('candidate')}/></div><div hidden={role!=='hr'}><HRViews {...roleView('hr')}/></div><div hidden={role!=='manager'}><ManagerViews {...roleView('manager')}/></div></motion.div><div className="hv-handoff"><span><Sparkles size={15}/>Другая сторона этого процесса</span><button onClick={()=>go(next[role].id)}>{next[role].label}<ArrowRight size={15}/></button></div></main></div></div>
 {walk&&<div className="hv-walk"><span>Путь найма <strong>{journey.indexOf(view)>=0?journey.indexOf(view)+1:'•'} / {journey.length}</strong></span><div>{journey.map((id,i)=><button key={id} className={view===id?'active':''} title={views.find(v=>v.id===id)?.name} aria-label={`Шаг ${i+1}: ${views.find(v=>v.id===id)?.name}`} onClick={()=>go(id)}>{i+1}</button>)}</div><button onClick={()=>setWalk(false)}>Скрыть маршрут</button></div>}
 {toast&&<div className="hv-toast" role="status"><Check size={18}/><span>{toast}</span><button onClick={()=>setToast('')} aria-label="Закрыть уведомление">×</button></div>}
 </div></MotionConfig>;
}
function ShieldIcon(){return <span className="hv-mini-mark">HR</span>}
