import type {ReactNode} from 'react';
import {ArrowUpRight,Check,ChevronRight,Search} from 'lucide-react';
export function Button({children,onClick,secondary=false,disabled=false}:{children:ReactNode;onClick?:()=>void;secondary?:boolean;disabled?:boolean}){return <button className={`hv-button ${secondary?'secondary':''}`} disabled={disabled} onClick={onClick}>{children}</button>}
export function Badge({children,tone='neutral'}:{children:ReactNode;tone?:'neutral'|'green'|'amber'|'purple'}){return <span className={`hv-badge ${tone}`}>{children}</span>}
export function Panel({title,aside,children,className=''}:{title?:string;aside?:ReactNode;children:ReactNode;className?:string}){return <section className={`hv-panel ${className}`}>{title&&<div className="hv-panel-head"><h3>{title}</h3>{aside}</div>}{children}</section>}
export function PageTitle({eyebrow,title,description,action}:{eyebrow?:string;title:string;description?:string;action?:ReactNode}){return <div className="hv-page-title"><div>{eyebrow&&<div className="hv-eyebrow">{eyebrow}</div>}<h1>{title}</h1>{description&&<p>{description}</p>}</div>{action}</div>}
export function Field({label,value,onChange,multiline=false}:{label:string;value:string;onChange:(value:string)=>void;multiline?:boolean}){return <label className="hv-field"><span>{label}</span>{multiline?<textarea value={value} onChange={e=>onChange(e.target.value)} rows={3}/>:<input value={value} onChange={e=>onChange(e.target.value)}/>}</label>}
export function Stat({label,value,note}:{label:string;value:string;note?:string}){return <div className="hv-stat"><span>{label}</span><strong>{value}</strong>{note&&<small>{note}</small>}</div>}
export function Row({title,detail,aside,onClick}:{title:string;detail?:string;aside?:ReactNode;onClick?:()=>void}){const inside=<><div><strong>{title}</strong>{detail&&<p>{detail}</p>}</div><div className="hv-row-aside">{aside}{onClick&&<ChevronRight size={16}/>}</div></>;return onClick?<button className="hv-row" onClick={onClick}>{inside}</button>:<div className="hv-row">{inside}</div>}
export function Note({children}:{children:ReactNode}){return <div className="hv-note">{children}</div>}
export function Avatar({initials,large=false}:{initials:string;large?:boolean}){return <span className={`hv-avatar ${large?'large':''}`}>{initials}</span>}
export function SearchField({value,onChange,placeholder='Поиск'}:{value:string;onChange:(value:string)=>void;placeholder?:string}){return <label className="hv-search"><Search size={17}/><input aria-label={placeholder} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)}/></label>}
export function Steps({items,current}:{items:string[];current:number}){return <div className="hv-steps">{items.map((t,i)=><div key={t} className={i<=current?'done':''}><span>{i<current?<Check size={12}/>:i+1}</span>{t}</div>)}</div>}
export function LinkButton({children,onClick}:{children:ReactNode;onClick:()=>void}){return <button className="hv-text-button" onClick={onClick}>{children}<ArrowUpRight size={15}/></button>}
