import type {Meta,StoryObj} from '@storybook/react-vite';
import {HRVisionLab} from './scenes/hr-vision/HRVisionLab';
const meta={title:'HR Vision/Агентский подбор',id:'hr-vision-agency',component:HRVisionLab,parameters:{layout:'fullscreen',controls:{disable:true}},args:{initialView:'E04'}} satisfies Meta<typeof HRVisionLab>;
export default meta;
type Story=StoryObj<typeof meta>;
export const Overview:Story={name:'00 Все участники · живой пример'};
export const E01:Story={name:'E01 Обзор найма',args:{initialView:'E01'}};
export const E02:Story={name:'E02 Задача и роль',args:{initialView:'E02'}};
export const E03:Story={name:'E03 Подборка кандидатов',args:{initialView:'E03'}};
export const E04:Story={name:'E04 Карточка кандидата',args:{initialView:'E04'}};
export const E05:Story={name:'E05 Оффер и выход',args:{initialView:'E05'}};
export const H01:Story={name:'H01 Вакансии и задачи',args:{initialView:'H01'}};
export const H02:Story={name:'H02 Поток кандидатов',args:{initialView:'H02'}};
export const H03:Story={name:'H03 Проверка кандидата',args:{initialView:'H03'}};
export const H04:Story={name:'H04 Встречи и следующие шаги',args:{initialView:'H04'}};
export const A01:Story={name:'A01 Компании и сигналы',args:{initialView:'A01'}};
export const A02:Story={name:'A02 Заказы и команда',args:{initialView:'A02'}};
export const A03:Story={name:'A03 База кандидатов',args:{initialView:'A03'}};
export const A04:Story={name:'A04 Интервью и оценка',args:{initialView:'A04'}};
export const A05:Story={name:'A05 Подборки клиентам',args:{initialView:'A05'}};
export const A06:Story={name:'A06 Сопровождение',args:{initialView:'A06'}};
export const C01:Story={name:'C01 Приглашение',args:{initialView:'C01'}};
export const C02:Story={name:'C02 Интервью и задания',args:{initialView:'C02'}};
export const C03:Story={name:'C03 Моя вакансия',args:{initialView:'C03'}};
export const C04:Story={name:'C04 Мой поиск',args:{initialView:'C04'}};
